[package]
name = "blockchain-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
csv = "1.3.1"
env_logger = "0.11.8"
log = "0.4.27"
rand = "0.8"
rand_distr = "0.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
